// <auto-generated />
namespace EntityModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MessageMasterandProdectinaddField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessageMasterandProdectinaddField));
        
        string IMigrationMetadata.Id
        {
            get { return "202312061019491_MessageMasterandProdectinaddField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
