// <auto-generated />
namespace EntityModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class usermasternullableremoveforhradmin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usermasternullableremoveforhradmin));
        
        string IMigrationMetadata.Id
        {
            get { return "202405270614239_usermasternullableremoveforhradmin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
