// <auto-generated />
namespace EntityModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addQbTotalAmountandupdateddateinInvoicePaymentStatusDetailstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addQbTotalAmountandupdateddateinInvoicePaymentStatusDetailstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202503240724542_addQbTotalAmountandupdateddateinInvoicePaymentStatusDetailstable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
